# Generated by Django 4.0.5 on 2022-07-22 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FinalCoderApp', '0005_remove_comentario_nombre_comentario_autor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('avatar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='FinalCoderApp.avatar')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
