# Generated by Django 4.0.5 on 2022-07-23 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalCoderApp', '0007_alter_avatar_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/'),
        ),
    ]
