# Generated by Django 4.0.5 on 2022-07-24 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinalCoderApp', '0008_alter_avatar_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerPerfil',
        ),
    ]
